site_name: power
site_url: https://goessl.github.io/power/
site_author: Sebastian Gössl
site_description: An exponentiation Python package.

repo_name: goessl/power
repo_url: https://github.com/goessl/power

copyright: Copyright &copy; 2025 Sebastian Gössl

nav:
  - Home: index.md

theme:
  name: material
  features:
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to system preference

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/goessl/
      name: goessl on Github
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/lordgoessl/
      name: goessl on Instagram

plugins:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          heading_level: 3
          members_order: source
          show_labels: false
          show_root_toc_entry: false
          show_symbol_type_heading: true
          docstring_style: numpy

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - meta
